Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate Interface Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate Interface Reference
リバーシプレイデリゲート
Public Member Functions
ReversiPlayDelegate (ReversiPlayInterface i)
コンストラクタ
FuncsJson ViewMsgDlg (String title, String msg)
メッセージダイアログ
FuncsJson DrawSingle (int y, int x, int sts, int bk, String text)
1マス描画
FuncsJson CurColMsg (String text)
現在の色メッセージ
FuncsJson CurStsMsg (String text)
現在のステータスメッセージ
FuncsJson Wait (int time)
ウェイト
Private Attributes
final ReversiPlayInterface impl
デリゲート
Detailed Description
リバーシプレイデリゲート
Definition at line 27 of file ReversiPlayDelegate.java.
Constructor & Destructor Documentation
ReversiPlayDelegate()
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.ReversiPlayDelegate (ReversiPlayInterface i)
コンストラクタ
Parameters
[in] ReversiPlayInterface i
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 40 of file ReversiPlayDelegate.java.
Member Function Documentation
CurColMsg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.CurColMsg (String text)
現在の色メッセージ
Parameters
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 87 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.CurColMsgLocal().
CurStsMsg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.CurStsMsg (String text)
現在のステータスメッセージ
Parameters
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 101 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.CurStsMsgLocal().
DrawSingle()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.DrawSingle (int y, int x, int sts, int bk, String text)
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 73 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.DrawSingleLocal().
ViewMsgDlg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.ViewMsgDlg (String title, String msg)
メッセージダイアログ
Parameters
[in] String title タイトル
[in] String msg メッセージ
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 55 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.ViewMsgDlgLocal().
Wait()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.Wait (int time)
ウェイト
Parameters
[in] int time ウェイト時間(msec)
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 115 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.WaitLocal().
The documentation for this interface was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/ReversiPlayDelegate.java