Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz Class Reference
リバーシ解析クラス
Public Member Functions
int getMin ()
ゲッター
void setMin (int min)
セッター
int getMax ()
ゲッター
void setMax (int max)
セッター
double getAvg ()
ゲッター
void setAvg (double avg)
セッター
int getPointCnt ()
ゲッター
void setPointCnt (int pointCnt)
セッター
int getEdgeCnt ()
ゲッター
void setEdgeCnt (int edgeCnt)
セッター
int getEdgeSideOneCnt ()
ゲッター
void setEdgeSideOneCnt (int edgeSideOneCnt)
セッター
int getEdgeSideTwoCnt ()
ゲッター
void setEdgeSideTwoCnt (int edgeSideTwoCnt)
セッター
int getEdgeSideThreeCnt ()
ゲッター
void setEdgeSideThreeCnt (int edgeSideThreeCnt)
セッター
int getEdgeSideOtherCnt ()
ゲッター
void setEdgeSideOtherCnt (int edgeSideOtherCnt)
セッター
int getOwnMin ()
ゲッター
void setOwnMin (int ownMin)
セッター
int getOwnMax ()
ゲッター
void setOwnMax (int ownMax)
セッター
double getOwnAvg ()
ゲッター
void setOwnAvg (double ownAvg)
セッター
int getOwnPointCnt ()
ゲッター
void setOwnPointCnt (int ownPointCnt)
セッター
int getOwnEdgeCnt ()
ゲッター
void setOwnEdgeCnt (int ownEdgeCnt)
セッター
int getOwnEdgeSideOneCnt ()
ゲッター
void setOwnEdgeSideOneCnt (int ownEdgeSideOneCnt)
セッター
int getOwnEdgeSideTwoCnt ()
ゲッター
void setOwnEdgeSideTwoCnt (int ownEdgeSideTwoCnt)
セッター
int getOwnEdgeSideThreeCnt ()
ゲッター
void setOwnEdgeSideThreeCnt (int ownEdgeSideThreeCnt)
セッター
int getOwnEdgeSideOtherCnt ()
ゲッター
void setOwnEdgeSideOtherCnt (int ownEdgeSideOtherCnt)
セッター
int getBadPoint ()
ゲッター
void setBadPoint (int badPoint)
セッター
int getGoodPoint ()
ゲッター
void setGoodPoint (int goodPoint)
セッター
ReversiAnz ()
コンストラクタ
void reset ()
リセット
Private Attributes
int min
最小値
int max
最大値
double avg
平均
int pointCnt
置けるポイント数
int edgeCnt
角を取れるポイント数
int edgeSideOneCnt
角一つ前を取れるポイント数
int edgeSideTwoCnt
角二つ前を取れるポイント数
int edgeSideThreeCnt
角三つ前を取れるポイント数
int edgeSideOtherCnt
それ以外を取れるポイント数
int ownMin
最小値
int ownMax
最大値
double ownAvg
平均
int ownPointCnt
置けるポイント数
int ownEdgeCnt
角を取れるポイント数
int ownEdgeSideOneCnt
角一つ前を取れるポイント数
int ownEdgeSideTwoCnt
角二つ前を取れるポイント数
int ownEdgeSideThreeCnt
角三つ前を取れるポイント数
int ownEdgeSideOtherCnt
それ以外を取れるポイント数
int badPoint
悪手ポイント
int goodPoint
良手ポイント
Detailed Description
リバーシ解析クラス
Definition at line 27 of file ReversiAnz.java.
Constructor & Destructor Documentation
ReversiAnz()
public jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.ReversiAnz ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2014.07.23
Definition at line 558 of file ReversiAnz.java.
Member Function Documentation
getAvg()
double jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getAvg ()
ゲッター
Returns
double avg
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 108 of file ReversiAnz.java.
getBadPoint()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getBadPoint ()
ゲッター
Returns
int badPoint
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 508 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getEdgeCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getEdgeCnt ()
ゲッター
Returns
int edgeCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 158 of file ReversiAnz.java.
getEdgeSideOneCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getEdgeSideOneCnt ()
ゲッター
Returns
int edgeSideOneCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 183 of file ReversiAnz.java.
getEdgeSideOtherCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getEdgeSideOtherCnt ()
ゲッター
Returns
int edgeSideOtherCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 258 of file ReversiAnz.java.
getEdgeSideThreeCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getEdgeSideThreeCnt ()
ゲッター
Returns
int edgeSideThreeCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 233 of file ReversiAnz.java.
getEdgeSideTwoCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getEdgeSideTwoCnt ()
ゲッター
Returns
int edgeSideTwoCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 208 of file ReversiAnz.java.
getGoodPoint()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getGoodPoint ()
ゲッター
Returns
int goodPoint
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 533 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getMax()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getMax ()
ゲッター
Returns
int max
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 83 of file ReversiAnz.java.
getMin()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getMin ()
ゲッター
Returns
int min
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 58 of file ReversiAnz.java.
getOwnAvg()
double jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnAvg ()
ゲッター
Returns
double ownAvg
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 333 of file ReversiAnz.java.
getOwnEdgeCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnEdgeCnt ()
ゲッター
Returns
int ownEdgeCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 383 of file ReversiAnz.java.
getOwnEdgeSideOneCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnEdgeSideOneCnt ()
ゲッター
Returns
int ownEdgeSideOneCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 408 of file ReversiAnz.java.
getOwnEdgeSideOtherCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnEdgeSideOtherCnt ()
ゲッター
Returns
int ownEdgeSideOtherCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 483 of file ReversiAnz.java.
getOwnEdgeSideThreeCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnEdgeSideThreeCnt ()
ゲッター
Returns
int ownEdgeSideThreeCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 458 of file ReversiAnz.java.
getOwnEdgeSideTwoCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnEdgeSideTwoCnt ()
ゲッター
Returns
int ownEdgeSideTwoCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 433 of file ReversiAnz.java.
getOwnMax()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnMax ()
ゲッター
Returns
int ownMax
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 308 of file ReversiAnz.java.
getOwnMin()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnMin ()
ゲッター
Returns
int ownMin
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 283 of file ReversiAnz.java.
getOwnPointCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getOwnPointCnt ()
ゲッター
Returns
int ownPointCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 358 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getPointCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.getPointCnt ()
ゲッター
Returns
int pointCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 133 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
reset()
public void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.reset ()
リセット
Returns
ありません
Author
Yuta Yoshinaga
Date
2014.07.23
Definition at line 571 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversi(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.ReversiAnz().
setAvg()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setAvg (double avg)
セッター
Parameters
[in] double avg
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 121 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setBadPoint()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setBadPoint (int badPoint)
セッター
Parameters
[in] int badPoint
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 521 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setEdgeCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setEdgeCnt (int edgeCnt)
セッター
Parameters
[in] int edgeCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 171 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setEdgeSideOneCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setEdgeSideOneCnt (int edgeSideOneCnt)
セッター
Parameters
[in] int edgeSideOneCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 196 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setEdgeSideOtherCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setEdgeSideOtherCnt (int edgeSideOtherCnt)
セッター
Parameters
[in] int edgeSideOtherCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 271 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setEdgeSideThreeCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setEdgeSideThreeCnt (int edgeSideThreeCnt)
セッター
Parameters
[in] int edgeSideThreeCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 246 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setEdgeSideTwoCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setEdgeSideTwoCnt (int edgeSideTwoCnt)
セッター
Parameters
[in] int edgeSideTwoCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 221 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setGoodPoint()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setGoodPoint (int goodPoint)
セッター
Parameters
[in] int goodPoint
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 546 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setMax()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setMax (int max)
セッター
Parameters
[in] int max
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 96 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setMin()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setMin (int min)
セッター
Parameters
[in] int min
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 71 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnAvg()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnAvg (double ownAvg)
セッター
Parameters
[in] double ownAvg
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 346 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnEdgeCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnEdgeCnt (int ownEdgeCnt)
セッター
Parameters
[in] int ownEdgeCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 396 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnEdgeSideOneCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnEdgeSideOneCnt (int ownEdgeSideOneCnt)
セッター
Parameters
[in] int ownEdgeSideOneCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 421 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnEdgeSideOtherCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnEdgeSideOtherCnt (int ownEdgeSideOtherCnt)
セッター
Parameters
[in] int ownEdgeSideOtherCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 496 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnEdgeSideThreeCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnEdgeSideThreeCnt (int ownEdgeSideThreeCnt)
セッター
Parameters
[in] int ownEdgeSideThreeCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 471 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnEdgeSideTwoCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnEdgeSideTwoCnt (int ownEdgeSideTwoCnt)
セッター
Parameters
[in] int ownEdgeSideTwoCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 446 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnMax()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnMax (int ownMax)
セッター
Parameters
[in] int ownMax
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 321 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnMin()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnMin (int ownMin)
セッター
Parameters
[in] int ownMin
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 296 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setOwnPointCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setOwnPointCnt (int ownPointCnt)
セッター
Parameters
[in] int ownPointCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 371 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
setPointCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiAnz.setPointCnt (int pointCnt)
セッター
Parameters
[in] int pointCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 146 of file ReversiAnz.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite().
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/ReversiAnz.java