Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay Class Reference
リバーシプレイクラス
Public Member Functions
Reversi getmReversi ()
ゲッター
void setmReversi (Reversi mReversi)
セッター
ReversiSetting getmSetting ()
ゲッター
void setmSetting (ReversiSetting mSetting)
セッター
int getmCurColor ()
ゲッター
void setmCurColor (int mCurColor)
セッター
ReversiPoint [] getmCpu ()
void setmCpu (ReversiPoint[] mCpu)
セッター
ReversiPoint [] getmEdge ()
void setmEdge (ReversiPoint[] mEdge)
セッター
int getmPassEnaB ()
ゲッター
void setmPassEnaB (int mPassEnaB)
セッター
int getmPassEnaW ()
ゲッター
void setmPassEnaW (int mPassEnaW)
セッター
int getmPassEnaL ()
ゲッター
void setmPassEnaL (int mPassEnaL)
セッター
int getmPassEnaR ()
ゲッター
void setmPassEnaR (int mPassEnaR)
セッター
int getmGameEndSts ()
ゲッター
void setmGameEndSts (int mGameEndSts)
セッター
int getmPlayLock ()
ゲッター
void setmPlayLock (int mPlayLock)
セッター
Random getR ()
ゲッター
void setR (Random r)
セッター
ReversiPlayDelegate getmDelegate ()
ゲッター
void setmDelegate (ReversiPlayDelegate mDelegate)
セッター
CallbacksJson getmCallbacks ()
ゲッター
void setmCallbacks (CallbacksJson mCallbacks)
セッター
ReversiPlay ()
コンストラクタ
void reversiPlay (int y, int x)
リバーシプレイ
void reversiPlaySub (int cpuEna, int tmpCol)
リバーシプレイサブ
void reversiPlayEnd ()
リバーシプレイ終了
void reversiPlayPass (int color)
リバーシプレイパス
int reversiPlayCpu (int color, int cpuEna)
リバーシプレイコンピューター
void drawUpdate (int assist)
マス描画更新
void drawUpdateForcibly (int assist)
マス描画強制更新
void reset ()
リセット処理
int getNextCol (int color)
次の色取得
int gameEndAnimExec ()
ゲーム終了アニメーション
void sendDrawMsg (int y, int x)
描画メッセージ送信
void sendDrawInfoMsg (int y, int x)
情報描画メッセージ送信
Private Member Functions
void execMessage (int what, Object obj)
メッセージ
void ViewMsgDlgLocal (String title, String msg)
メッセージダイアログ
void DrawSingleLocal (int y, int x, int sts, int bk, String text)
1マス描画
void CurColMsgLocal (String text)
現在の色メッセージ
void CurStsMsgLocal (String text)
現在のステータスメッセージ
void WaitLocal (int time)
ウェイト
Private Attributes
Reversi mReversi
リバーシクラス
ReversiSetting mSetting
リバーシ設定クラス
int mCurColor
現在の色
ReversiPoint [] mCpu
CPU用ワーク
ReversiPoint [] mEdge
CPU用角マスワーク
int mPassEnaB
黒のパス有効フラグ
int mPassEnaW
白のパス有効フラグ
int mPassEnaL
青のパス有効フラグ
int mPassEnaR
赤のパス有効フラグ
int mGameEndSts
ゲーム終了ステータス
int mPlayLock
プレイロック
Random r
乱数
ReversiPlayDelegate mDelegate
デリゲート
CallbacksJson mCallbacks
コールバック
Detailed Description
リバーシプレイクラス
Definition at line 28 of file ReversiPlay.java.
Constructor & Destructor Documentation
ReversiPlay()
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.ReversiPlay ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 403 of file ReversiPlay.java.
Member Function Documentation
CurColMsgLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.CurColMsgLocal (String text) private
現在の色メッセージ
Parameters
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1340 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage().
CurStsMsgLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.CurStsMsgLocal (String text) private
現在のステータスメッセージ
Parameters
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1354 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage().
DrawSingleLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.DrawSingleLocal (int y, int x, int sts, int bk, String text) private
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1326 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage().
drawUpdate()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate (int assist)
マス描画更新
Parameters
[in] int assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 937 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
drawUpdateForcibly()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdateForcibly (int assist)
マス描画強制更新
Parameters
[in] int assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 970 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset().
execMessage()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage (int what, Object obj) private
メッセージ
Parameters
[in] int what
[in] Object obj
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1206 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdateForcibly(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayEnd(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.sendDrawInfoMsg(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.sendDrawMsg().
gameEndAnimExec()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec ()
ゲーム終了アニメーション
Returns
ウェイト時間
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1076 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayEnd().
getmCallbacks()
CallbacksJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmCallbacks ()
ゲッター
Returns
CallbacksJson mCallbacks
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 378 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.doPost().
getmCurColor()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmCurColor ()
ゲッター
Returns
int mCurColor
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 103 of file ReversiPlay.java.
getmDelegate()
ReversiPlayDelegate jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmDelegate ()
ゲッター
Returns
ReversiPlayDelegate mDelegate
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 353 of file ReversiPlay.java.
getmGameEndSts()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmGameEndSts ()
ゲッター
Returns
int mGameEndSts
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 278 of file ReversiPlay.java.
getmPassEnaB()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmPassEnaB ()
ゲッター
Returns
int mPassEnaB
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 178 of file ReversiPlay.java.
getmPassEnaL()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmPassEnaL ()
ゲッター
Returns
int mPassEnaL
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 228 of file ReversiPlay.java.
getmPassEnaR()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmPassEnaR ()
ゲッター
Returns
int mPassEnaR
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 253 of file ReversiPlay.java.
getmPassEnaW()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmPassEnaW ()
ゲッター
Returns
int mPassEnaW
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 203 of file ReversiPlay.java.
getmPlayLock()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmPlayLock ()
ゲッター
Returns
int mPlayLock
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 303 of file ReversiPlay.java.
getmReversi()
Reversi jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmReversi ()
ゲッター
Returns
Reversi mReversi
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 53 of file ReversiPlay.java.
getmSetting()
ReversiSetting jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getmSetting ()
ゲッター
Returns
ReversiSetting mSetting
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 78 of file ReversiPlay.java.
getNextCol()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getNextCol (int color)
次の色取得
Parameters
[in] int color 現在の色
Returns
次の色
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1058 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub().
getR()
Random jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.getR ()
ゲッター
Returns
Random r
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 328 of file ReversiPlay.java.
reset()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset ()
リセット処理
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 995 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.doPost().
reversiPlay()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay (int y, int x)
リバーシプレイ
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 433 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.doPost().
reversiPlayCpu()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu (int color, int cpuEna)
リバーシプレイコンピューター
Parameters
[in] int color CPU色
[in] int cpuEna CPU有効フラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 659 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub().
reversiPlayEnd()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayEnd ()
リバーシプレイ終了
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 572 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub().
reversiPlayPass()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayPass (int color)
リバーシプレイパス
Parameters
[in] int color パス色
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 637 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub().
reversiPlaySub()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub (int cpuEna, int tmpCol)
リバーシプレイサブ
Parameters
[in] int cpuEna
[in] int tmpCol
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 531 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay().
sendDrawInfoMsg()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.sendDrawInfoMsg (int y, int x)
情報描画メッセージ送信
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1187 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate().
sendDrawMsg()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.sendDrawMsg (int y, int x)
描画メッセージ送信
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1168 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
setmCallbacks()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmCallbacks (CallbacksJson mCallbacks)
セッター
Parameters
[in] CallbacksJson mCallbacks
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 391 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.doPost().
setmCpu()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmCpu (ReversiPoint [] mCpu)
セッター
Parameters
[in] ReversiPoint[] mCpu
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 141 of file ReversiPlay.java.
setmCurColor()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmCurColor (int mCurColor)
セッター
Parameters
[in] int mCurColor
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 116 of file ReversiPlay.java.
setmDelegate()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmDelegate (ReversiPlayDelegate mDelegate)
セッター
Parameters
[in] ReversiPlayDelegate mDelegate
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 366 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.doPost().
setmEdge()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmEdge (ReversiPoint [] mEdge)
セッター
Parameters
[in] ReversiPoint[] mEdge
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 166 of file ReversiPlay.java.
setmGameEndSts()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmGameEndSts (int mGameEndSts)
セッター
Parameters
[in] int mGameEndSts
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 291 of file ReversiPlay.java.
setmPassEnaB()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmPassEnaB (int mPassEnaB)
セッター
Parameters
[in] int mPassEnaB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 191 of file ReversiPlay.java.
setmPassEnaL()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmPassEnaL (int mPassEnaL)
セッター
Parameters
[in] int mPassEnaL
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 241 of file ReversiPlay.java.
setmPassEnaR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmPassEnaR (int mPassEnaR)
セッター
Parameters
[in] int mPassEnaR
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 266 of file ReversiPlay.java.
setmPassEnaW()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmPassEnaW (int mPassEnaW)
セッター
Parameters
[in] int mPassEnaW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 216 of file ReversiPlay.java.
setmPlayLock()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmPlayLock (int mPlayLock)
セッター
Parameters
[in] int mPlayLock
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 316 of file ReversiPlay.java.
setmReversi()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmReversi (Reversi mReversi)
セッター
Parameters
[in] Reversi mReversi
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 66 of file ReversiPlay.java.
setmSetting()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setmSetting (ReversiSetting mSetting)
セッター
Parameters
[in] ReversiSetting mSetting
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 91 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.doPost().
setR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.setR (Random r)
セッター
Parameters
[in] Random r
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 341 of file ReversiPlay.java.
ViewMsgDlgLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.ViewMsgDlgLocal (String title, String msg) private
メッセージダイアログ
Parameters
[in] String title タイトル
[in] String msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1308 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayEnd().
WaitLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.WaitLocal (int time) private
ウェイト
Parameters
[in] int time ウェイト時間(msec)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1368 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayEnd().
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/ReversiPlay.java