Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory Class Reference
リバーシ履歴クラス
Public Member Functions
ReversiPoint getPoint ()
ゲッター
void setPoint (ReversiPoint point)
セッター
int getColor ()
ゲッター
void setColor (int color)
セッター
ReversiHistory ()
コンストラクタ
void reset ()
リセット
Private Attributes
ReversiPoint point
リバーシポイント
int color
カラー
Detailed Description
リバーシ履歴クラス
Definition at line 27 of file ReversiHistory.java.
Constructor & Destructor Documentation
ReversiHistory()
public jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.ReversiHistory ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2014.07.23
Definition at line 90 of file ReversiHistory.java.
Member Function Documentation
getColor()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.getColor ()
ゲッター
Returns
int color
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 65 of file ReversiHistory.java.
getPoint()
ReversiPoint jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.getPoint ()
ゲッター
Returns
ReversiPoint point
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 40 of file ReversiHistory.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuSts().
reset()
public void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.reset ()
リセット
Returns
ありません
Author
Yuta Yoshinaga
Date
2014.07.23
Definition at line 103 of file ReversiHistory.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.ReversiHistory().
setColor()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.setColor (int color)
セッター
Parameters
[in] int color
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 78 of file ReversiHistory.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuSts().
setPoint()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.setPoint (ReversiPoint point)
セッター
Parameters
[in] ReversiPoint point
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 53 of file ReversiHistory.java.
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/ReversiHistory.java