Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.CallbacksJson Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.CallbacksJson Class Reference
コールバックJSONクラス
Public Member Functions
ArrayList< FuncsJson > getFuncs ()
ゲッター
void setFuncs (ArrayList< FuncsJson > funcs)
セッター
CallbacksJson ()
コンストラクタ
Private Attributes
ArrayList< FuncsJson > funcs
ファンクションズ
Detailed Description
コールバックJSONクラス
Definition at line 28 of file CallbacksJson.java.
Constructor & Destructor Documentation
CallbacksJson()
public jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.CallbacksJson.CallbacksJson ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 65 of file CallbacksJson.java.
Member Function Documentation
getFuncs()
ArrayList< FuncsJson > jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.CallbacksJson.getFuncs ()
ゲッター
Returns
ArrayList<FuncsJson> funcs
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 40 of file CallbacksJson.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.CurColMsgLocal(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.CurStsMsgLocal(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.DrawSingleLocal(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.ViewMsgDlgLocal(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.WaitLocal().
setFuncs()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.CallbacksJson.setFuncs (ArrayList< FuncsJson > funcs)
セッター
Parameters
[in] ArrayList<FuncsJson> funcs
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 53 of file CallbacksJson.java.
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/CallbacksJson.java