Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi Class Reference
リバーシクラス
Public Member Functions
int [][] getmMasuSts ()
void setmMasuSts (int[][] mMasuSts)
セッター
int [][] getmMasuStsOld ()
void setmMasuStsOld (int[][] mMasuStsOld)
セッター
int [][] getmMasuStsEnaB ()
void setmMasuStsEnaB (int[][] mMasuStsEnaB)
セッター
int [][] getmMasuStsCntB ()
void setmMasuStsCntB (int[][] mMasuStsCntB)
セッター
int [][] getmMasuStsPassB ()
void setmMasuStsPassB (int[][] mMasuStsPassB)
セッター
ReversiAnz [][] getmMasuStsAnzB ()
void setmMasuStsAnzB (ReversiAnz[][] mMasuStsAnzB)
セッター
ReversiPoint [] getmMasuPointB ()
void setmMasuPointB (ReversiPoint[] mMasuPointB)
セッター
int getmMasuPointCntB ()
ゲッター
void setmMasuPointCntB (int mMasuPointCntB)
セッター
int getmMasuBetCntB ()
ゲッター
void setmMasuBetCntB (int mMasuBetCntB)
セッター
int [][] getmMasuStsEnaW ()
void setmMasuStsEnaW (int[][] mMasuStsEnaW)
セッター
int [][] getmMasuStsCntW ()
void setmMasuStsCntW (int[][] mMasuStsCntW)
セッター
int [][] getmMasuStsPassW ()
void setmMasuStsPassW (int[][] mMasuStsPassW)
セッター
ReversiAnz [][] getmMasuStsAnzW ()
void setmMasuStsAnzW (ReversiAnz[][] mMasuStsAnzW)
セッター
ReversiPoint [] getmMasuPointW ()
void setmMasuPointW (ReversiPoint[] mMasuPointW)
セッター
int getmMasuPointCntW ()
ゲッター
void setmMasuPointCntW (int mMasuPointCntW)
セッター
int getmMasuBetCntW ()
ゲッター
void setmMasuBetCntW (int mMasuBetCntW)
セッター
int [][] getmMasuStsEnaL ()
void setmMasuStsEnaL (int[][] mMasuStsEnaL)
セッター
int [][] getmMasuStsCntL ()
void setmMasuStsCntL (int[][] mMasuStsCntL)
セッター
int [][] getmMasuStsPassL ()
void setmMasuStsPassL (int[][] mMasuStsPassL)
セッター
ReversiAnz [][] getmMasuStsAnzL ()
void setmMasuStsAnzL (ReversiAnz[][] mMasuStsAnzL)
セッター
ReversiPoint [] getmMasuPointL ()
void setmMasuPointL (ReversiPoint[] mMasuPointL)
セッター
int getmMasuPointCntL ()
ゲッター
void setmMasuPointCntL (int mMasuPointCntL)
セッター
int getmMasuBetCntL ()
ゲッター
void setmMasuBetCntL (int mMasuBetCntL)
セッター
int [][] getmMasuStsEnaR ()
void setmMasuStsEnaR (int[][] mMasuStsEnaR)
セッター
int [][] getmMasuStsCntR ()
void setmMasuStsCntR (int[][] mMasuStsCntR)
セッター
int [][] getmMasuStsPassR ()
void setmMasuStsPassR (int[][] mMasuStsPassR)
セッター
ReversiAnz [][] getmMasuStsAnzR ()
void setmMasuStsAnzR (ReversiAnz[][] mMasuStsAnzR)
セッター
ReversiPoint [] getmMasuPointR ()
void setmMasuPointR (ReversiPoint[] mMasuPointR)
セッター
int getmMasuPointCntR ()
ゲッター
void setmMasuPointCntR (int mMasuPointCntR)
セッター
int getmMasuBetCntR ()
ゲッター
void setmMasuBetCntR (int mMasuBetCntR)
セッター
int getmMasuCnt ()
ゲッター
void setmMasuCnt (int mMasuCnt)
セッター
int getmMasuCntMax ()
ゲッター
void setmMasuCntMax (int mMasuCntMax)
セッター
ReversiHistory [] getmMasuHist ()
void setmMasuHist (ReversiHistory[] mMasuHist)
セッター
int getmMasuHistCur ()
ゲッター
void setmMasuHistCur (int mMasuHistCur)
セッター
Reversi (int masuCnt, int masuMax)
コンストラクタ
Reversi ()
コンストラクタ
void reset ()
リセット
void AnalysisReversi (int bPassEna, int wPassEna, int lPassEna, int rPassEna)
解析を行う
int getMasuSts (int y, int x)
マスステータスを取得
int getMasuStsOld (int y, int x)
以前のマスステータスを取得
int getMasuStsEna (int color, int y, int x)
指定座標に指定色を置けるかチェック
int getMasuStsCnt (int color, int y, int x)
指定座標の獲得コマ数取得
int getColorEna (int color)
指定色が現在置ける場所があるかチェック
int getGameEndSts ()
ゲーム終了かチェック
int setMasuSts (int color, int y, int x)
指定座標にコマを置く
int setMasuStsForcibly (int color, int y, int x)
指定座標にコマを強制的に置く
int setMasuCnt (int cnt)
マスの数変更
ReversiPoint getPoint (int color, int num)
ポイント座標取得
int getPointCnt (int color)
ポイント座標数取得
int getBetCnt (int color)
コマ数取得
int getPassEna (int color, int y, int x)
パス判定
ReversiHistory getHistory (int num)
履歴取得
int getHistoryCnt ()
履歴数取得
ReversiAnz getPointAnz (int color, int y, int x)
ポイント座標解析取得
int checkEdge (int color, int y, int x)
角の隣に置いても角を取られないマス検索
int getEdgeSideZero (int y, int x)
指定座標が角か取得
int getEdgeSideOne (int y, int x)
指定座標が角の一つ手前か取得
int getEdgeSideTwo (int y, int x)
指定座標が角の二つ手前か取得
int getEdgeSideThree (int y, int x)
指定座標が角の三つ以上手前か取得
Private Member Functions
int makeMasuSts (int color)
各コマの置ける場所等のステータス作成
void revMasuSts (int color, int y, int x)
コマをひっくり返す
int checkPara (int para, int min, int max)
パラメーター範囲チェック
void AnalysisReversiBlack ()
解析を行う(黒)
void AnalysisReversiWhite ()
解析を行う(白)
void AnalysisReversiBlue ()
解析を行う(青)
void AnalysisReversiRed ()
解析を行う(赤)
Private Attributes
int mMasuSts [][]
マスの状態
int mMasuStsOld [][]
以前のマスの状態
int mMasuStsEnaB [][]
黒の置ける場所
int mMasuStsCntB [][]
黒の獲得コマ数
int mMasuStsPassB [][]
黒が相手をパスさせる場所
ReversiAnz mMasuStsAnzB [][]
黒がその場所に置いた場合の解析結果
ReversiPoint mMasuPointB []
黒の置ける場所座標一覧
int mMasuPointCntB
黒の置ける場所座標一覧数
int mMasuBetCntB
黒コマ数
int mMasuStsEnaW [][]
白の置ける場所
int mMasuStsCntW [][]
白の獲得コマ数
int mMasuStsPassW [][]
白が相手をパスさせる場所
ReversiAnz mMasuStsAnzW [][]
白がその場所に置いた場合の解析結果
ReversiPoint mMasuPointW []
白の置ける場所座標一覧
int mMasuPointCntW
白の置ける場所座標一覧数
int mMasuBetCntW
白コマ数
int mMasuStsEnaL [][]
青の置ける場所
int mMasuStsCntL [][]
青の獲得コマ数
int mMasuStsPassL [][]
青が相手をパスさせる場所
ReversiAnz mMasuStsAnzL [][]
青がその場所に置いた場合の解析結果
ReversiPoint mMasuPointL []
青の置ける場所座標一覧
int mMasuPointCntL
青の置ける場所座標一覧数
int mMasuBetCntL
青コマ数
int mMasuStsEnaR [][]
赤の置ける場所
int mMasuStsCntR [][]
赤の獲得コマ数
int mMasuStsPassR [][]
赤が相手をパスさせる場所
ReversiAnz mMasuStsAnzR [][]
赤がその場所に置いた場合の解析結果
ReversiPoint mMasuPointR []
赤の置ける場所座標一覧
int mMasuPointCntR
赤の置ける場所座標一覧数
int mMasuBetCntR
赤コマ数
int mMasuCnt
縦横マス数
int mMasuCntMax
縦横マス最大数
ReversiHistory mMasuHist []
履歴
int mMasuHistCur
履歴現在位置
Detailed Description
リバーシクラス
Definition at line 27 of file Reversi.java.
Constructor & Destructor Documentation
Reversi() [1/2]
public jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.Reversi (int masuCnt, int masuMax)
コンストラクタ
Parameters
[in] int masuCnt 縦横マス数
[in] int masuMax 縦横マス最大数
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 924 of file Reversi.java.
Reversi() [2/2]
public jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.Reversi ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1009 of file Reversi.java.
Member Function Documentation
AnalysisReversi()
public void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversi (int bPassEna, int wPassEna, int lPassEna, int rPassEna)
解析を行う
Parameters
[in] int bPassEna 1=黒パス有効
[in] int wPassEna 1=白パス有効
[in] int lPassEna 1=青パス有効
[in] int rPassEna 1=赤パス有効
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2335 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
AnalysisReversiBlack()
private void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack () private
解析を行う(黒)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1505 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversi().
AnalysisReversiBlue()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue () private
解析を行う(青)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1915 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversi().
AnalysisReversiRed()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed () private
解析を行う(赤)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2123 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversi().
AnalysisReversiWhite()
private void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite () private
解析を行う(白)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1710 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversi().
checkEdge()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.checkEdge (int color, int y, int x)
角の隣に置いても角を取られないマス検索
Parameters
[in] int color 色
[in] int y Y座標
[in] int x X座標
Returns
0 : 取られる それ以外 : 取られない
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2734 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
checkPara()
private int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.checkPara (int para, int min, int max) private
パラメーター範囲チェック
Parameters
[in] int para チェックパラメーター
[in] int min パラメーター最小値
[in] int max パラメーター最大値
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1490 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getHistory(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getMasuSts(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getMasuStsCnt(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getMasuStsEna(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getMasuStsOld(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getPassEna(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getPoint(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getPointAnz(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuCnt().
getBetCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getBetCnt (int color)
コマ数取得
Parameters
[in] int color コマ色
Returns
コマ数取得
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2631 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayEnd(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub().
getColorEna()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getColorEna (int color)
指定色が現在置ける場所があるかチェック
Parameters
[in] int color コマ色
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2468 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getGameEndSts(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub().
getEdgeSideOne()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getEdgeSideOne (int y, int x)
指定座標が角の一つ手前か取得
Parameters
[in] int y Y座標
[in] int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2872 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getEdgeSideThree()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getEdgeSideThree (int y, int x)
指定座標が角の三つ以上手前か取得
Parameters
[in] int y Y座標
[in] int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2936 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getEdgeSideTwo()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getEdgeSideTwo (int y, int x)
指定座標が角の二つ手前か取得
Parameters
[in] int y Y座標
[in] int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2904 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getEdgeSideZero()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getEdgeSideZero (int y, int x)
指定座標が角か取得
Parameters
[in] int y Y座標
[in] int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2848 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getGameEndSts()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getGameEndSts ()
ゲーム終了かチェック
Returns
0 : 続行 それ以外 : ゲーム終了
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2490 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub().
getHistory()
public ReversiHistory jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getHistory (int num)
履歴取得
Parameters
[in] int num ポイント
Returns
履歴 null : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2676 of file Reversi.java.
getHistoryCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getHistoryCnt ()
履歴数取得
Returns
履歴数
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2693 of file Reversi.java.
getMasuSts()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getMasuSts (int y, int x)
マスステータスを取得
Parameters
[in] int y 取得するマスのY座標
[in] int x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2389 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.checkEdge(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage().
getMasuStsCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getMasuStsCnt (int color, int y, int x)
指定座標の獲得コマ数取得
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
-1 : 失敗 それ以外 : 獲得コマ数
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2447 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getMasuStsEna()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getMasuStsEna (int color, int y, int x)
指定座標に指定色を置けるかチェック
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
1 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2424 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getColorEna(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuSts().
getMasuStsOld()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getMasuStsOld (int y, int x)
以前のマスステータスを取得
Parameters
[in] int y 取得するマスのY座標
[in] int x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 2406 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate().
getmMasuBetCntB()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuBetCntB ()
ゲッター
Returns
int mMasuBetCntB
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 272 of file Reversi.java.
getmMasuBetCntL()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuBetCntL ()
ゲッター
Returns
int mMasuBetCntL
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 622 of file Reversi.java.
getmMasuBetCntR()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuBetCntR ()
ゲッター
Returns
int mMasuBetCntR
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 797 of file Reversi.java.
getmMasuBetCntW()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuBetCntW ()
ゲッター
Returns
int mMasuBetCntW
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 447 of file Reversi.java.
getmMasuCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuCnt ()
ゲッター
Returns
int mMasuCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 822 of file Reversi.java.
getmMasuCntMax()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuCntMax ()
ゲッター
Returns
int mMasuCntMax
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 847 of file Reversi.java.
getmMasuHistCur()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuHistCur ()
ゲッター
Returns
int mMasuHistCur
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 897 of file Reversi.java.
getmMasuPointCntB()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuPointCntB ()
ゲッター
Returns
int mMasuPointCntB
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 247 of file Reversi.java.
getmMasuPointCntL()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuPointCntL ()
ゲッター
Returns
int mMasuPointCntL
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 597 of file Reversi.java.
getmMasuPointCntR()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuPointCntR ()
ゲッター
Returns
int mMasuPointCntR
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 772 of file Reversi.java.
getmMasuPointCntW()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getmMasuPointCntW ()
ゲッター
Returns
int mMasuPointCntW
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 422 of file Reversi.java.
getPassEna()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getPassEna (int color, int y, int x)
パス判定
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
パス判定
0 : NOT PASS
1 : PASS
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2655 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getPoint()
public ReversiPoint jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getPoint (int color, int num)
ポイント座標取得
Parameters
[in] int color コマ色
[in] int num ポイント
Returns
ポイント座標 null : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2591 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getPointAnz()
public ReversiAnz jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getPointAnz (int color, int y, int x)
ポイント座標解析取得
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
ポイント座標解析 null : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2711 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getPointCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.getPointCnt (int color)
ポイント座標数取得
Parameters
[in] int color コマ色
Returns
ポイント座標数取得
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2612 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
makeMasuSts()
private int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.makeMasuSts (int color) private
各コマの置ける場所等のステータス作成
Parameters
[in] int color ステータスを作成するコマ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1077 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversi(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuSts().
reset()
public void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.reset ()
リセット
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1022 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.Reversi(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuCnt().
revMasuSts()
private void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.revMasuSts (int color, int y, int x) private
コマをひっくり返す
Parameters
[in] int color ひっくり返す元コマ
[in] int y ひっくり返す元コマのY座標
[in] int x ひっくり返す元コマのX座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1318 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuSts().
setMasuCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuCnt (int cnt)
マスの数変更
Parameters
[in] int cnt マスの数
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2567 of file Reversi.java.
setMasuSts()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuSts (int color, int y, int x)
指定座標にコマを置く
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2511 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
setMasuStsForcibly()
public int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuStsForcibly (int color, int y, int x)
指定座標にコマを強制的に置く
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 2547 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec().
setmMasuBetCntB()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuBetCntB (int mMasuBetCntB)
セッター
Parameters
[in] int mMasuBetCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 285 of file Reversi.java.
setmMasuBetCntL()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuBetCntL (int mMasuBetCntL)
セッター
Parameters
[in] int mMasuBetCntL
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 635 of file Reversi.java.
setmMasuBetCntR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuBetCntR (int mMasuBetCntR)
セッター
Parameters
[in] int mMasuBetCntR
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 810 of file Reversi.java.
setmMasuBetCntW()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuBetCntW (int mMasuBetCntW)
セッター
Parameters
[in] int mMasuBetCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 460 of file Reversi.java.
setmMasuCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuCnt (int mMasuCnt)
セッター
Parameters
[in] int mMasuCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 835 of file Reversi.java.
setmMasuCntMax()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuCntMax (int mMasuCntMax)
セッター
Parameters
[in] int mMasuCntMax
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 860 of file Reversi.java.
setmMasuHist()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuHist (ReversiHistory [] mMasuHist)
セッター
Parameters
[in] ReversiHistory[] mMasuHist
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 885 of file Reversi.java.
setmMasuHistCur()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuHistCur (int mMasuHistCur)
セッター
Parameters
[in] int mMasuHistCur
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 910 of file Reversi.java.
setmMasuPointB()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuPointB (ReversiPoint [] mMasuPointB)
セッター
Parameters
[in] ReversiPoint[] mMasuPointB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 235 of file Reversi.java.
setmMasuPointCntB()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuPointCntB (int mMasuPointCntB)
セッター
Parameters
[in] int mMasuPointCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 260 of file Reversi.java.
setmMasuPointCntL()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuPointCntL (int mMasuPointCntL)
セッター
Parameters
[in] int mMasuPointCntL
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 610 of file Reversi.java.
setmMasuPointCntR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuPointCntR (int mMasuPointCntR)
セッター
Parameters
[in] int mMasuPointCntR
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 785 of file Reversi.java.
setmMasuPointCntW()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuPointCntW (int mMasuPointCntW)
セッター
Parameters
[in] int mMasuPointCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 435 of file Reversi.java.
setmMasuPointL()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuPointL (ReversiPoint [] mMasuPointL)
セッター
Parameters
[in] ReversiPoint[] mMasuPointL
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 585 of file Reversi.java.
setmMasuPointR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuPointR (ReversiPoint [] mMasuPointR)
セッター
Parameters
[in] ReversiPoint[] mMasuPointR
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 760 of file Reversi.java.
setmMasuPointW()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuPointW (ReversiPoint [] mMasuPointW)
セッター
Parameters
[in] ReversiPoint[] mMasuPointW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 410 of file Reversi.java.
setmMasuSts()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuSts (int mMasuSts[][])
セッター
Parameters
[in] int[][] mMasuSts
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 85 of file Reversi.java.
setmMasuStsAnzB()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsAnzB (ReversiAnz mMasuStsAnzB[][])
セッター
Parameters
[in] ReversiAnz[][] mMasuStsAnzB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 210 of file Reversi.java.
setmMasuStsAnzL()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsAnzL (ReversiAnz mMasuStsAnzL[][])
セッター
Parameters
[in] ReversiAnz[][] mMasuStsAnzL
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 560 of file Reversi.java.
setmMasuStsAnzR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsAnzR (ReversiAnz mMasuStsAnzR[][])
セッター
Parameters
[in] ReversiAnz[][] mMasuStsAnzR
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 735 of file Reversi.java.
setmMasuStsAnzW()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsAnzW (ReversiAnz mMasuStsAnzW[][])
セッター
Parameters
[in] ReversiAnz[][] mMasuStsAnzW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 385 of file Reversi.java.
setmMasuStsCntB()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsCntB (int mMasuStsCntB[][])
セッター
Parameters
[in] int[][] mMasuStsCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 160 of file Reversi.java.
setmMasuStsCntL()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsCntL (int mMasuStsCntL[][])
セッター
Parameters
[in] int[][] mMasuStsCntL
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 510 of file Reversi.java.
setmMasuStsCntR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsCntR (int mMasuStsCntR[][])
セッター
Parameters
[in] int[][] mMasuStsCntR
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 685 of file Reversi.java.
setmMasuStsCntW()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsCntW (int mMasuStsCntW[][])
セッター
Parameters
[in] int[][] mMasuStsCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 335 of file Reversi.java.
setmMasuStsEnaB()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsEnaB (int mMasuStsEnaB[][])
セッター
Parameters
[in] int[][] mMasuStsEnaB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 135 of file Reversi.java.
setmMasuStsEnaL()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsEnaL (int mMasuStsEnaL[][])
セッター
Parameters
[in] int[][] mMasuStsEnaL
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 485 of file Reversi.java.
setmMasuStsEnaR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsEnaR (int mMasuStsEnaR[][])
セッター
Parameters
[in] int[][] mMasuStsEnaR
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 660 of file Reversi.java.
setmMasuStsEnaW()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsEnaW (int mMasuStsEnaW[][])
セッター
Parameters
[in] int[][] mMasuStsEnaW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 310 of file Reversi.java.
setmMasuStsOld()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsOld (int mMasuStsOld[][])
セッター
Parameters
[in] int[][] mMasuStsOld
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 110 of file Reversi.java.
setmMasuStsPassB()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsPassB (int mMasuStsPassB[][])
セッター
Parameters
[in] int[][] mMasuStsPassB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 185 of file Reversi.java.
setmMasuStsPassL()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsPassL (int mMasuStsPassL[][])
セッター
Parameters
[in] int[][] mMasuStsPassL
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 535 of file Reversi.java.
setmMasuStsPassR()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsPassR (int mMasuStsPassR[][])
セッター
Parameters
[in] int[][] mMasuStsPassR
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 710 of file Reversi.java.
setmMasuStsPassW()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setmMasuStsPassW (int mMasuStsPassW[][])
セッター
Parameters
[in] int[][] mMasuStsPassW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 360 of file Reversi.java.
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/Reversi.java