Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPoint Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPoint Class Reference
リバーシポイントクラス
Public Member Functions
int getX ()
ゲッター
void setX (int x)
セッター
int getY ()
ゲッター
void setY (int y)
セッター
ReversiPoint ()
コンストラクタ
Private Attributes
int x
X座標
int y
Y座標
Detailed Description
リバーシポイントクラス
Definition at line 27 of file ReversiPoint.java.
Constructor & Destructor Documentation
ReversiPoint()
public jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPoint.ReversiPoint ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 90 of file ReversiPoint.java.
Member Function Documentation
getX()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPoint.getX ()
ゲッター
Returns
int x
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 40 of file ReversiPoint.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getY()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPoint.getY ()
ゲッター
Returns
int y
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 65 of file ReversiPoint.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiBlue(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiRed(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
setX()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPoint.setX (int x)
セッター
Parameters
[in] int x
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 53 of file ReversiPoint.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.makeMasuSts(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.sendDrawInfoMsg(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.sendDrawMsg(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuSts().
setY()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPoint.setY (int y)
セッター
Parameters
[in] int y
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 78 of file ReversiPoint.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.makeMasuSts(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiHistory.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.sendDrawInfoMsg(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.sendDrawMsg(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.Reversi.setMasuSts().
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/ReversiPoint.java