Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting Class Reference
アプリ設定クラス
Public Member Functions
int getmMode ()
ゲッター
void setmMode (int mMode)
セッター
int getmType ()
ゲッター
void setmType (int mType)
セッター
int getmPlayer ()
ゲッター
void setmPlayer (int mPlayer)
セッター
int getmAssist ()
ゲッター
void setmAssist (int mAssist)
セッター
int getmGameSpd ()
ゲッター
void setmGameSpd (int mGameSpd)
セッター
int getmEndAnim ()
ゲッター
void setmEndAnim (int mEndAnim)
セッター
int getmMasuCntMenu ()
ゲッター
void setmMasuCntMenu (int mMasuCntMenu)
セッター
int getmMasuCnt ()
ゲッター
void setmMasuCnt (int mMasuCnt)
セッター
int getmPlayCpuInterVal ()
ゲッター
void setmPlayCpuInterVal (int mPlayCpuInterVal)
セッター
int getmPlayDrawInterVal ()
ゲッター
void setmPlayDrawInterVal (int mPlayDrawInterVal)
セッター
int getmEndDrawInterVal ()
ゲッター
void setmEndDrawInterVal (int mEndDrawInterVal)
セッター
int getmEndInterVal ()
ゲッター
void setmEndInterVal (int mEndInterVal)
セッター
String getmPlayerColor1 ()
ゲッター
void setmPlayerColor1 (String mPlayerColor1)
セッター
String getmPlayerColor2 ()
ゲッター
void setmPlayerColor2 (String mPlayerColor2)
セッター
String getmPlayerColor3 ()
ゲッター
void setmPlayerColor3 (String mPlayerColor3)
セッター
String getmPlayerColor4 ()
ゲッター
void setmPlayerColor4 (String mPlayerColor4)
セッター
String getmBackGroundColor ()
ゲッター
void setmBackGroundColor (String mBackGroundColor)
セッター
String getmBorderColor ()
ゲッター
void setmBorderColor (String mBorderColor)
セッター
ReversiSetting ()
コンストラクタ
void reset ()
リセット
Private Attributes
int mMode
現在のモード
int mType
現在のタイプ
int mPlayer
プレイヤーの色
int mAssist
アシスト
int mGameSpd
ゲームスピード
int mEndAnim
ゲーム終了アニメーション
int mMasuCntMenu
マスの数
int mMasuCnt
マスの数
int mPlayCpuInterVal
CPU対戦時のインターバル(msec)
int mPlayDrawInterVal
描画のインターバル(msec)
int mEndDrawInterVal
終了アニメーション描画のインターバル(msec)
int mEndInterVal
終了アニメーションのインターバル(msec)
String mPlayerColor1
プレイヤー1の色
String mPlayerColor2
プレイヤー2の色
String mPlayerColor3
プレイヤー3の色
String mPlayerColor4
プレイヤー4の色
String mBackGroundColor
背景の色
String mBorderColor
枠線の色
Detailed Description
アプリ設定クラス
Definition at line 27 of file ReversiSetting.java.
Constructor & Destructor Documentation
ReversiSetting()
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.ReversiSetting ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 506 of file ReversiSetting.java.
Member Function Documentation
getmAssist()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmAssist ()
ゲッター
Returns
int mAssist
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 131 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlaySub().
getmBackGroundColor()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmBackGroundColor ()
ゲッター
Returns
String mBackGroundColor
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 456 of file ReversiSetting.java.
getmBorderColor()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmBorderColor ()
ゲッター
Returns
String mBorderColor
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 481 of file ReversiSetting.java.
getmEndAnim()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmEndAnim ()
ゲッター
Returns
int mEndAnim
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 181 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayEnd().
getmEndDrawInterVal()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmEndDrawInterVal ()
ゲッター
Returns
int mEndDrawInterVal
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 306 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec().
getmEndInterVal()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmEndInterVal ()
ゲッター
Returns
int mEndInterVal
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 331 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec().
getmGameSpd()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmGameSpd ()
ゲッター
Returns
int mGameSpd
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 156 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset().
getmMasuCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmMasuCnt ()
ゲッター
Returns
int mMasuCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 231 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.gameEndAnimExec(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
getmMasuCntMenu()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmMasuCntMenu ()
ゲッター
Returns
int mMasuCntMenu
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 206 of file ReversiSetting.java.
getmMode()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmMode ()
ゲッター
Returns
int mMode
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 56 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.execMessage(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayEnd().
getmPlayCpuInterVal()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmPlayCpuInterVal ()
ゲッター
Returns
int mPlayCpuInterVal
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 256 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay().
getmPlayDrawInterVal()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmPlayDrawInterVal ()
ゲッター
Returns
int mPlayDrawInterVal
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 281 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.drawUpdate().
getmPlayer()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmPlayer ()
ゲッター
Returns
int mPlayer
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 106 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset().
getmPlayerColor1()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmPlayerColor1 ()
ゲッター
Returns
String mPlayerColor1
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 356 of file ReversiSetting.java.
getmPlayerColor2()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmPlayerColor2 ()
ゲッター
Returns
String mPlayerColor2
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 381 of file ReversiSetting.java.
getmPlayerColor3()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmPlayerColor3 ()
ゲッター
Returns
String mPlayerColor3
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 406 of file ReversiSetting.java.
getmPlayerColor4()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmPlayerColor4 ()
ゲッター
Returns
String mPlayerColor4
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 431 of file ReversiSetting.java.
getmType()
int jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.getmType ()
ゲッター
Returns
int mType
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 81 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reversiPlayCpu().
reset()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.reset ()
リセット
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 519 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.ReversiSetting().
setmAssist()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmAssist (int mAssist)
セッター
Parameters
[in] int mAssist
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 144 of file ReversiSetting.java.
setmBackGroundColor()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmBackGroundColor (String mBackGroundColor)
セッター
Parameters
[in] String mBackGroundColor
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 469 of file ReversiSetting.java.
setmBorderColor()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmBorderColor (String mBorderColor)
セッター
Parameters
[in] String mBorderColor
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 494 of file ReversiSetting.java.
setmEndAnim()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmEndAnim (int mEndAnim)
セッター
Parameters
[in] int mEndAnim
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 194 of file ReversiSetting.java.
setmEndDrawInterVal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmEndDrawInterVal (int mEndDrawInterVal)
セッター
Parameters
[in] int mEndDrawInterVal
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 319 of file ReversiSetting.java.
setmEndInterVal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmEndInterVal (int mEndInterVal)
セッター
Parameters
[in] int mEndInterVal
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 344 of file ReversiSetting.java.
setmGameSpd()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmGameSpd (int mGameSpd)
セッター
Parameters
[in] int mGameSpd
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 169 of file ReversiSetting.java.
setmMasuCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmMasuCnt (int mMasuCnt)
セッター
Parameters
[in] int mMasuCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 244 of file ReversiSetting.java.
setmMasuCntMenu()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmMasuCntMenu (int mMasuCntMenu)
セッター
Parameters
[in] int mMasuCntMenu
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 219 of file ReversiSetting.java.
setmMode()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmMode (int mMode)
セッター
Parameters
[in] int mMode
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 69 of file ReversiSetting.java.
setmPlayCpuInterVal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmPlayCpuInterVal (int mPlayCpuInterVal)
セッター
Parameters
[in] int mPlayCpuInterVal
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 269 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset().
setmPlayDrawInterVal()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmPlayDrawInterVal (int mPlayDrawInterVal)
セッター
Parameters
[in] int mPlayDrawInterVal
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 294 of file ReversiSetting.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlay.reset().
setmPlayer()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmPlayer (int mPlayer)
セッター
Parameters
[in] int mPlayer
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 119 of file ReversiSetting.java.
setmPlayerColor1()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmPlayerColor1 (String mPlayerColor1)
セッター
Parameters
[in] String mPlayerColor1
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 369 of file ReversiSetting.java.
setmPlayerColor2()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmPlayerColor2 (String mPlayerColor2)
セッター
Parameters
[in] String mPlayerColor2
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 394 of file ReversiSetting.java.
setmPlayerColor3()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmPlayerColor3 (String mPlayerColor3)
セッター
Parameters
[in] String mPlayerColor3
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 419 of file ReversiSetting.java.
setmPlayerColor4()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmPlayerColor4 (String mPlayerColor4)
セッター
Parameters
[in] String mPlayerColor4
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 444 of file ReversiSetting.java.
setmType()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiSetting.setmType (int mType)
セッター
Parameters
[in] int mType
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 94 of file ReversiSetting.java.
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/ReversiSetting.java