Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson Class Reference
ファンクションJSONクラス
Public Member Functions
String getFunc ()
ゲッター
void setFunc (String func)
セッター
String getParam1 ()
ゲッター
void setParam1 (String param1)
セッター
String getParam2 ()
ゲッター
void setParam2 (String param2)
セッター
String getParam3 ()
ゲッター
void setParam3 (String param3)
セッター
String getParam4 ()
ゲッター
void setParam4 (String param4)
セッター
String getParam5 ()
ゲッター
void setParam5 (String param5)
セッター
FuncsJson ()
コンストラクタ
Private Attributes
String func
ファンクション
String param1
パラメーター1
String param2
パラメーター2
String param3
パラメーター3
String param4
パラメーター4
String param5
パラメーター5
Detailed Description
ファンクションJSONクラス
Definition at line 27 of file FuncsJson.java.
Constructor & Destructor Documentation
FuncsJson()
public jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.FuncsJson ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 194 of file FuncsJson.java.
Member Function Documentation
getFunc()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.getFunc ()
ゲッター
Returns
String func
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 44 of file FuncsJson.java.
getParam1()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.getParam1 ()
ゲッター
Returns
String param1
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 69 of file FuncsJson.java.
getParam2()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.getParam2 ()
ゲッター
Returns
String param2
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 94 of file FuncsJson.java.
getParam3()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.getParam3 ()
ゲッター
Returns
String param3
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 119 of file FuncsJson.java.
getParam4()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.getParam4 ()
ゲッター
Returns
String param4
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 144 of file FuncsJson.java.
getParam5()
String jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.getParam5 ()
ゲッター
Returns
String param5
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 169 of file FuncsJson.java.
setFunc()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.setFunc (String func)
セッター
Parameters
[in] String func
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 57 of file FuncsJson.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.CurColMsg(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.CurStsMsg(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.DrawSingle(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.ViewMsgDlg(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.Wait().
setParam1()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.setParam1 (String param1)
セッター
Parameters
[in] String param1
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 82 of file FuncsJson.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.CurColMsg(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.CurStsMsg(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.DrawSingle(), jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.ViewMsgDlg(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.Wait().
setParam2()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.setParam2 (String param2)
セッター
Parameters
[in] String param2
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 107 of file FuncsJson.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.DrawSingle(), and jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.ViewMsgDlg().
setParam3()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.setParam3 (String param3)
セッター
Parameters
[in] String param3
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 132 of file FuncsJson.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.DrawSingle().
setParam4()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.setParam4 (String param4)
セッター
Parameters
[in] String param4
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 157 of file FuncsJson.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.DrawSingle().
setParam5()
void jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.FuncsJson.setParam5 (String param5)
セッター
Parameters
[in] String param5
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 182 of file FuncsJson.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.DrawSingle().
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/FuncsJson.java