Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayInterface Interface Reference
jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayInterface Interface Reference
リバーシプレイインターフェース
Public Member Functions
FuncsJson ViewMsgDlg (String title, String msg)
メッセージダイアログ
FuncsJson DrawSingle (int y, int x, int sts, int bk, String text)
1マス描画
FuncsJson CurColMsg (String text)
現在の色メッセージ
FuncsJson CurStsMsg (String text)
現在のステータスメッセージ
FuncsJson Wait (int time)
ウェイト
Detailed Description
リバーシプレイインターフェース
Definition at line 25 of file ReversiPlayInterface.java.
Member Function Documentation
CurColMsg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayInterface.CurColMsg (String text)
現在の色メッセージ
Parameters
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implemented in jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.CurColMsg().
CurStsMsg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayInterface.CurStsMsg (String text)
現在のステータスメッセージ
Parameters
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implemented in jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.CurStsMsg().
DrawSingle()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayInterface.DrawSingle (int y, int x, int sts, int bk, String text)
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implemented in jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.DrawSingle().
ViewMsgDlg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayInterface.ViewMsgDlg (String title, String msg)
メッセージダイアログ
Parameters
[in] String title タイトル
[in] String msg メッセージ
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implemented in jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.ViewMsgDlg().
Wait()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayInterface.Wait (int time)
ウェイト
Parameters
[in] int time ウェイト時間(msec)
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implemented in jp.gr.java_conf.yuta_yoshinaga.reversi4color.controller.FrontController.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi4color.model.ReversiPlayDelegate.Wait().
The documentation for this interface was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi4color/model/ReversiPlayInterface.java